name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "demo-calculator"
      IMAGE_TAG: "dev-v1"

    steps:
    - name: login to acr and build image
      run: |
        cd .
        ls -la
        docker images
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker login ${{secrets.AZ_REGISTRY}} -u ${{secrets.AZ_SERVICE_ID}} -p ${{secrets.AZ_SERVICE_PASS}} 
        echo "Login Successful"
        docker images
      
#     - name: Tag the image
#       run: docker tag $IMAGE_NAME ${{secrets.AZ_REGISTRY}}/$IMAGE_NAME:$IMAGE_TAG
    - name : Push to acr
      run : docker push $IMAGE:$IMAGE_TAG
